### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nerdy-nakul**

### CODE REVIEW

**Comment by SANTHOSH17-DOT** [comment]
Looks cool. I'm merging this PR

**Comment by SANTHOSH17-DOT** [comment]
Is this contribution under JWOC?@nerdy-nakul

**Comment by nerdy-nakul** [comment]
> Is this contribution under JWOC?@nerdy-nakul

Yes.

**Comment by nerdy-nakul** [comment]
> Is this contribution under JWOC?@nerdy-nakul

@SANTHOSH17-DOT sorry, it is under issue with SWOC tag.
I'm participating in both.

**Comment by SANTHOSH17-DOT** [comment]
Oh cool

**Comment by SANTHOSH17-DOT** [comment]
Solves #11

**Comment by SANTHOSH17-DOT** [comment]
Thank you very much for your contribution @nerdy-nakul

**Comment by nerdy-nakul** [comment]
> Thank you very much for your contribution @nerdy-nakul

You're welcome!
It was my pleasure to contribute. Just let me know if you need any assistance with documentation work.

**Pull request merged**
