### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nerdy-nakul**

### CODE REVIEW

**Comment by nerdy-nakul** [comment]
> In the contribution section, mention that they should branch out from the dev branch instead of the main branch.

do i need to do something ??

**Comment by SANTHOSH17-DOT** [comment]
You have made your changes in the main branch in your fork. I don't want that to happen. So contributors should create a branch from the dev branch in their fork.

**Comment by nerdy-nakul** [comment]
> You have made your changes in the main branch in your fork. I don't want that to happen. So contributors should create a branch from the dev branch in their fork.

done!!

**Comment by SANTHOSH17-DOT** [comment]
* Fork the repository.
    * [dev branch](https://github.com/SANTHOSH17-DOT/HODL/tree/dev)
 * Clone the forked repository to your local machine.
 * Create a new branch for your changes:
   * `git checkout -b <branch-name> dev`
  
  Kindly update the md into this

**Comment by nerdy-nakul** [comment]
> * Fork the repository.
> 
>     * Clone the forked repository to your local machine.
> 
>     * Create a new branch for your changes from the dev branch:
>       
>       * `git checkout -b <branch-name> dev`
> 
> 
> Kindly update the md into this

updated the README.md as requested.

**Comment by SANTHOSH17-DOT** [comment]
Kindly squash the commits into a single commit

**Comment by nerdy-nakul** [comment]
> Kindly squash the commits into a single commit

I'm still facing the same issue that I was facing earlier.
May I close this PR and raise a new one?

**Comment by SANTHOSH17-DOT** [comment]
Okay

**Pull request closed without merging**
