### PR TITLE
Updated the README

### PR DESCRIPTION
**Pull request by nerdy-nakul**

### CODE REVIEW

**Comment by SANTHOSH17-DOT** [comment]
Update network and contract address
Network - Goerli (chain id: 5)
Contract address - 0x6d119824Eb9c06c02242FFFaB3A8F6775958032F

Remove the chrome extension part from the readme.

Also, add instruction that every pr should be raised to the dev branch

Rest looks cool
@nerdy-nakul

**Comment by nerdy-nakul** [comment]
> Update network and contract address Network - Goerli (chain id: 5) Contract address - 0x6d119824Eb9c06c02242FFFaB3A8F6775958032F
> 
> Remove the chrome extension part from the readme.
> 
> Also, add instruction that every pr should be raised to the dev branch
> 
> Rest looks cool @nerdy-nakul

okay @SANTHOSH17-DOT

**Comment by nerdy-nakul** [comment]
I have made the changes as requested, please review once @SANTHOSH17-DOT

**Comment by SANTHOSH17-DOT** [comment]
Looks cool

**Comment by nerdy-nakul** [comment]
> Looks cool!!! Could you squash your commits into a single commit?
Sorry, I'm a beginner.
I dont know how to do that. If you can guide me I would be able to do that.

**Comment by SANTHOSH17-DOT** [comment]
Sure. There's a reset command in git. You have to use that. 
Look into this [post ](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together)for a reference

**Comment by nerdy-nakul** [comment]
> Sure. There's a reset command in git. You have to use that. Look into this [post ](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together)for a reference

I'm not able to use git squash command, is there any other way of doing this?
or should i close this pull request and make another pull request with only one commit?

**Comment by SANTHOSH17-DOT** [comment]
There isn't any command called `git squash`. You have to git reset first and then commit. Refer the link given above

**Comment by nerdy-nakul** [comment]
> There isn't any command called `git squash`. You have to git reset first and then commit. Refer the link given above

I'm not able to do this, still facing the same issue. 
Should i make another PR and close this one ?
It will be more easier for me.

**Comment by SANTHOSH17-DOT** [comment]
Okay

**Pull request closed without merging**
